### ISSUE TITLE
New Business Goal is placed.

### ISSUE THREAD

**Issue by jose598** [bryapuch/SII-WORKSHOPS-Vive_Facil_II#4]
Dear support team, we are satisfied about your hard work during this last year. On this new year we want to be bigger and better. In the meeting with the Accounting Department and Business Intelligent Group, we proposed some changes with the intention of improving our service and getting more customers. The new business rule establishes: If the customer is married and has more than 30 years old but younger than 60, then $50 must be decreased to the base premium for each one, however if the customer is single, woman and older than 60 years old , she will receive a discount for around $50.

You need to know that all rules should be maintained how it was coming. Our request should be added to the existing one and the result should be calculated with all rules applied.

**Comment by bryapuch** [comment]
Now, we will proceed to process the request @HectorRizzo will be assigned analyst, @bryapuch will develop the solution and @alcokond will perform the tests

**Comment by jose598** [comment]
@bryapuch  Thank you

**Comment by HectorRizzo** [comment]
@jose598 Added the
[CostAnalysis.pdf](https://github.com/bryapuch/SII-WORKSHOPS-Vive_Facil_II/files/7917591/CostAnalysis.pdf) to be checked.

**Comment by jose598** [comment]
Continue with the next step @HectorRizzo

**Comment by HectorRizzo** [comment]
The solution for the new requirements has been completed: 
https://github.com/bryapuch/SII-WORKSHOPS-Vive_Facil_II/blob/bc2888f29bb4b26e7f89a0ca5da40ffa33f60d70/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L21

and 

https://github.com/bryapuch/SII-WORKSHOPS-Vive_Facil_II/blob/bc2888f29bb4b26e7f89a0ca5da40ffa33f60d70/ec.edu.espol.workshops/lib/src/main/java/ec/edu/espol/workshops/CarInsurance.java#L24

@alcokond

**Comment by jose598** [comment]
What are you doing? @HectorRizzo 
I can't see the changed that I requested or please tell me where they are.

**Comment by jose598** [comment]
Are you still working on this issue? @alcokond @HectorRizzo @bryapuch

**Comment by jose598** [comment]
I will close this issue, because the deadline is over. 

I didn't receive a solution to this issue.
